### ISSUE TITLE
Empty record causes a case class to be generated without parenthesis (compile time error)

### ISSUE THREAD

**Issue by calvinlfer** [julianpeeters/sbt-avrohugger#12]
Hey Julian,

I'm trying to model a Calculator using event sourcing. I want to add a Reset event that takes no class parameters so just `case class Reset()` so I use an empty message. 

Here is my `avdl`
```
@namespace("com.experiments.calculator")
protocol MyApplication {
    record Added {
        int value;
    }

    record Subtracted {
        int value;
    }

    record Divided {
        int value;
    }

    record Multiplied {
        int value;
    }

    record Reset {}
}
```

All generated case classes work with the exception of `Reset`. Instead of generating `case class Reset()`, it generates `case class Reset` which is invalid in Scala 2.11.
I'm most likely doing something wrong so is there a better way to go about this?

I'm using the `sbtavrohugger.SbtAvrohugger.avroSettings` setting

Also one more question, I wanted these generated case classes to inherit from an Event `trait`. Is it possible to do so via the `avdl` or other settings?

Cheers and thanks for everything
Cal

**Comment by julianpeeters** [comment]
> Instead of generating case class Reset(), it generates case class Reset

Oops, this is just an oversight on my part. I Can't find a legitimate reference, but I believe it should generate a case object rather than an empty case class, no? I expect to have time to fix by the start of next week. Thanks for reporting.

>  I wanted these generated case classes to inherit from an Event trait

This thread may be relevant: https://github.com/julianpeeters/avrohugger/issues/19

Cheers,
Julian

**Comment by referentiallytransparent** [comment]
A case object would be even better :+1: 

Thanks a lot Julian!

**Comment by referentiallytransparent** [comment]
Regarding the trait question, I was just using an empty Event trait to associate all classes to a common parent. It used to be a `sealed trait` before for pattern matching safety but I don't think I can achieve that now since the classes are generated elsewhere. I'm not sure whether the typeclass pattern would help here.

**Comment by julianpeeters** [comment]
Hey Cal, sorry for the delay. If you're still in need of this feature, it is now available in avrohugger version 0.9.5, sbt-avrohugger version 0.9.8.

Turned out that Scalavro (and possibly other libs) couldn't handle case objects, so I ended up using empty case classes.

Evolutionary compatibility doesn't depend on Scala/Java/other representation, but rather only the avro side of things (i.e. "can an avro schema be used to read avro binary"), so no worries there.

Regarding the trait question, I think you're right: sealed traits would be great, and I don't think typeclasses will get us there. So far my use cases have not dealt with protocols, but its seems like they were built for this purpose. I've opened a [ticket](https://github.com/julianpeeters/avrohugger/issues/32) in avrohugger, likely another week out.

Cheers and happy avroing

**Comment by referentiallytransparent** [comment]
Great work Julian! Thanks for doing this. Your explanation makes perfect sense. Looking forward to seeing protocol support, this would be so awesome!

Keeping a close eye on the ticket.
Have a great day

**Comment by julianpeeters** [comment]
Hey Cal! I'm back. 0.10.1 should be generating ADTs from protocols now, synching up with Maven Central shortly. 

Sounds like you're using `avroSettings`, but in case you're trying other formats then be forewarned that I have yet to support expanding existing ADT code `String`s (they're on my list though).
