### ISSUE TITLE
When cross-building is enabled, the code is generated only for one version

### ISSUE THREAD

**Issue by rabejens** [julianpeeters/sbt-avrohugger#36]
In my SBT project, my main Scala version is set to 2.11.8, but because I am also using Spark, I set up my project for cross-building for 2.10.6 and 2.11.8.

However, the `+avro:generate-specific` (the plus for crossbuild mode) puts the generated Scala code to `target/scala-2.10/src_managed/main/compiled_avro`. I manually have to copy it to the respective `scala_2.11` folder.

Without the copying, a `sbt +compile` works, but when using the project in Eclipse, I manually have to add the 2.10 folder to my project, otherwise it shows a lot of compiler errors.

Is it possible to tell the plugin to output the generated code to both directories?

**Comment by julianpeeters** [comment]
I hadn't run into this before, thanks for the report. sbt-avrohugger defers to sbt here, so I'm not sure of quick fix (and my eta to look closer is probably on a "months" timeframe). PRs accepted, course. In the meantime, I wonder if you might have success by [overriding](https://github.com/julianpeeters/sbt-avrohugger#changing-settings) `scalaSource`, so both Scala versions will (over)write to the same, non-`target`directory?

**Comment by rabejens** [comment]
What should I put into the `scalaSource` override? How are the paths resolved?

**Comment by julianpeeters** [comment]
if you override with `(scalaSource in avroConfig) := new java.io.File("src/scala/main/myscalaSource")`, then the code will be generated into `src/scala/main/myscalaSource` instead of `target/scala-2.10/src_managed/main/compiled_avro`. (Come to think of it tho, if you have enums im your schema, I'm not sure avrohugger will be smart enough -- my have to a add a method to avrohugger that (or derives) a `javaSource` as well.

Thanks for poking at this. The source override feature is modified from sbt-avro, so my familiarity with it is not perfect, please try these suggestions and report more specific errors for quickest help.

**Comment by rabejens** [comment]
I set:

```scala
(scalaSource in avroConfig) := new File("target/scala/src_managed/main/compiled_avro")
```

I then deleted all previously generated files.

But now, the source is generated in the `target` directory of my main sbt directory. However, I have a multi-project build. Do I have to set the path individually for each project or is there a wildcard like "relative to project directory"?

**Comment by julianpeeters** [comment]
Awesome, congrats and thanks for sharing!

**Comment by rabejens** [comment]
Hello, I am coming back to this one. I just upgraded to the newest avrohugger and now `avroConfig` is gone. Where is it now?

**Comment by julianpeeters** [comment]
ok great, thanks for the update!

**Comment by julianpeeters** [comment]
https://github.com/julianpeeters/sbt-avrohugger/pull/88
