### ISSUE TITLE
Release for sbt-1.0.0

### ISSUE THREAD

**Issue by snadorp** [julianpeeters/sbt-avrohugger#42]
Would be great to have an sbt-1.0.0 compatible release.

**Comment by julianpeeters** [comment]
Hi @snadorp,thanks for the request. I've got a draft nearly finished, but there are some breaking changes regarding:

1. all plugins must now be autoplugins, and currently there is a conflict if settings for more than one format are imported
2. request to remove avroConfig, according to sbt best practices, and so that different values can be set for different configs (e.g different avro source directories in Compile and Test)

Since I'd like to get feedback on these changes, a release may be a couple more weeks out.

**Comment by snadorp** [comment]
Great to hear, thanks for taking care! Let me know if I can help somehow.

**Comment by mohnishkodnani** [comment]
I just wanted to check if this was done and if any help is required.

**Comment by fkoehler** [comment]
We also need a sbt 1.0 version as well in order to upgrade our project. Are the issues above resolved? Is there a way one can help?

**Comment by julianpeeters** [comment]
@snadorp @mohnishkodnani @fkoehler Thanks for your patience, all, and thanks very much for your offers. avrohugger 0.17.0 for scala 2.12 (and sbt-avrohugger 1.0.0) is out now.
