### ISSUE TITLE
Trying to use sbt-avrohugger in Spark project, and unable to find plugin for Scala 2.11

### ISSUE THREAD

**Issue by chrisalbright** [julianpeeters/sbt-avrohugger#48]
Apache Spark is not yet built for 2.12 (I know...) so I still need to use scala 2.11.X, and there is no sbt-avrohugger for scala 2.11.

My build is looking for a version here:

https://repo1.maven.org/maven2/com/julianpeeters/sbt-avrohugger_2.11_1.0/2.0.0-RC4/sbt-avrohugger-2.0.0-RC4.pom

Which is (as you know) not available... 😬

Conversely, if I try to use Scala 2.12.X, I cannot find my Spark libs.

I've also tried downgrading to Scala 2.10 and sbt 0.13, to no avail; the same outcome - no spark libs compiled for 2.10.X

Would you be willing to publish a version for Scala 2.11?

**Comment by julianpeeters** [comment]
Hello!

There's no 2.11 version because there is no version of sbt that is on 2.11. I'm not familiar with your build tool; it may be fibbing, or maybe `addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "2.0.0-RC4")` is in your `build.sbt` instead of your `plugins.sbt`? 

If you're on sbt 1.X, then I'd expect that adding `addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "2.0.0-RC4")` to your `plugins.sbt` file should work, pulling in the correct 2.12 version: https://repo1.maven.org/maven2/com/julianpeeters/sbt-avrohugger_2.12_1.0/2.0.0-RC4/sbt-avrohugger-2.0.0-RC4.pom

Lemme know if this doesn't do the trick

**Comment by chrisalbright** [comment]
Looks like that did it. Thanks for the info, I'm very new to SBT and still trying to figure out how it works. Also, I'm apparently new to reading. I see the instructions now in the Readme pointing to plugins.sbt plain as day. Sorry for not properly RTFM'ing and thanks for not assuming I hadn't.
