### ISSUE TITLE
Cant seem to find the "avroScalaGenerateSpecific" in built.sbt

### ISSUE THREAD

**Issue by sachabarber** [julianpeeters/sbt-avrohugger#56]
I have the following structure in IntelliJ/SBT setup

my folder
- build.sbt
 - project
     - Deps.sbt
     - plugins.sbt
 - common
     - src
        - main
           - avro
              - userSchema.avsc
 - publisher
 - subscriber

The schema looks like this

```
{
    "namespace": "com.barber.kafka.avro",
     "type": "record",
     "name": "user",
     "fields":[
         {
            "name": "id", "type": "int"
         },
         {
            "name": "name",  "type": "string"
         }
     ]
}
```

**plugins.sbt** looks like this
`addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "2.0.0-RC10")`

And here is my **build.sbt** file (see how  its a multiproject SBT)

```import Deps._
import sbt.Keys.scalaVersion


lazy val root = (project in file(".")).
  aggregate(publisher, subscriber).
  settings(
    inThisBuild(List(
      organization := "com.barber",
      scalaVersion := "2.12.1",
      resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots",
      resolvers += "io.confluent" at "http://packages.confluent.io/maven/"
    )),
    name := "scala_kafka_specific_avro_example"
  )

lazy val publisher = (project in file ("publisher")).
  settings(
    name := "publisher",
    /* sourceGenerators in Compile += (avroScalaGenerateSpecific in Compile).taskValue, */
    libraryDependencies ++= Seq(
      kafka,
      avro,
      avroSerializer,
      logBack)
  ).dependsOn(common)

lazy val subscriber = (project in file ("subscriber")).
  settings(
    name := "subscriber",
      /* sourceGenerators in Compile += (avroScalaGenerateSpecific in Compile).taskValue, */
    libraryDependencies ++= Seq(
      kafka,
      avro,
      avroSerializer,
      logBack)
  ).dependsOn(publisher, common)

lazy val common = (project in file ("common")).
  settings(
    name := "common",
    /* sourceGenerators in Compile += (avroScalaGenerateSpecific in Compile).taskValue, */
    libraryDependencies ++= Seq(
      kafka,
      avro,
      avroSerializer,
      logBack)
  )
```

And the **Deps.sbt** file looks like this

```
import sbt._

object Deps {
  lazy val kafka = "org.apache.kafka" % "kafka_2.11" % "1.1.0"
  lazy val avro =  "org.apache.avro" % "avro" % "1.8.2"
  lazy val avroSerializer = "io.confluent" % "kafka-avro-serializer" % "3.2.1"
  lazy val logBack = "ch.qos.logback" %  "logback-classic" % "1.1.7"
}
```

The issue I am having is that the **build.sbt** file doesn't seem to know about the `avroScalaGenerateSpecific` task.

I know the plugin is working, as I can run this SBT command 

**sbt common/avroScalaGenerateSpecific**

And I get the correctly generated **SpecificRecordBasecase class** implementation in **src_managed** folder

**Comment by julianpeeters** [comment]
Sorry @sachabarber I'm not too familiar with intellij, tho I can't help but notice that, in your `build.sbt`, the the line that wires the task in to sourceGenerators in Compile is commented out : ` /* sourceGenerators in Compile += (avroScalaGenerateSpecific in Compile).taskValue, */` This might account for what you are experiencing since
a) the task would be available to run manually, but not automatically triggered with `compile`
b) classes manually generated into sourceManaged aren't automatically known to the compiler (IIRC its possible to tell sbt (and thus intellij, I suppose) where to look without wiring the task into Compile. Alternatively, the target directory can be set to a directory in `src`, where `compile` would be looking for source anyways)

This obviously doesn't explain how things worked without intellij, perhaps it was some combo of leftover classes from previous compiles + experiments commenting/uncommenting that line? Otherwise I'm stumped on that one.
