### ISSUE TITLE
Doesn't mangle/backtick reserved words

### ISSUE THREAD

**Issue by withinboredom** [julianpeeters/sbt-avrohugger#70]
Reproduce with the following file:

```avdl
protocol test {
  record Test {
    boolean `public`;
  }
}
```

Get the error:

```
java.lang.UnsupportedOperationException: `public` is a reserved keyword and cannot be used as field name
```

**Comment by julianpeeters** [comment]
Thanks for this report @withinboredom. I'll start with backtick, unless you have a preference. I'm a bit busy tho, timeframe is looking like 1-4 weeks.

**Comment by withinboredom** [comment]
If you can point me to the generation code, I can probably get it to generate code like

```scala
case class Test(private var _$$public) {
  def `public`: Boolean = _$$public
}
```

Which works with reflection/spark out of the box (I did this manually in my project for a few tables)

**Comment by julianpeeters** [comment]
That's very interesting, but that would be a new [format](https://github.com/julianpeeters/avrohugger/tree/master/avrohugger-core/src/main/scala/format) and I'm afraid I'm unable to support that currently. For a few reasons, but primarily because scripted tests are already too big and maxes out CI. The tests could likely be restructured, but main could also use a refactor (e.g. better intermediate representation) to gain the most benefit. But I'm not interested in rushing that timeline, I'd probably recommend forking avrohugger, if time is a concern.


If any of the currently supported formats will work for you, then adding backticks to reserved words 
```scala
case class Test(`public`: Boolean) 
```

is a matter of ensuring they are applied to `fieldName`, and I mention needing a better intermediate representation because doing so entails updating the [various formats](https://github.com/julianpeeters/avrohugger/search?q=fieldname&unscoped_q=fieldname) and updating the tests.
