### ISSUE TITLE
404 on maven 

### ISSUE THREAD

**Issue by omerholz** [julianpeeters/sbt-avrohugger#8]
Trying to download the plugin using sbt, I've noticed a failure:
```sbt.ResolveException: unresolved dependency: com.julianpeeters#sbt-avrohugger;0.5.0: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)```
Looking at maven, I've noticed I'm getting 404s for both 0.5.0 and 0.5.1:

```
curl -v http://repo1.maven.org/maven2/com/julianpeeters/sbt-avrohugger/0.5.1/
   Trying 199.27.76.209...
 Connected to repo1.maven.org (199.27.76.209) port 80 (#0)
 GET /maven2/com/julianpeeters/sbt-avrohugger/0.5.1/ HTTP/1.1
 Host: repo1.maven.org
 User-Agent: curl/7.43.0
 Accept: */*

 HTTP/1.1 404 Not Found
 Server: nginx
 Content-Type: text/html
 Via: 1.1 varnish
 Content-Length: 564
 Accept-Ranges: bytes
 Date: Sun, 08 Nov 2015 00:35:12 GMT
 Via: 1.1 varnish
 Age: 8
 Connection: keep-alive
 X-Served-By: cache-iad2142-IAD, cache-jfk1029-JFK
 X-Cache: HIT, HIT
 X-Cache-Hits: 1, 1
 X-Timer: S1446942912.330150,VS0,VE0
```

**Comment by julianpeeters** [comment]
Hi Omer,

I'm not able to reproduce the sbt resolveException. Would you mind trying again and reporting back if it still doesn't work?

The `curl` won't work because, apparently, hosting sbt-plugins is currently kind of a hack because plugin artifacts aren't true maven artifacts. Specifically, plugins get published as:

http://repo1.maven.org/maven2/com/julianpeeters/sbt-avrohugger_2.10_0.13/0.5.1/

(note the scala and sbt versions at the end of the project name).

**Comment by omerholz** [comment]
Closing the issue. I didn't noticed that 2.11 is not supported. This was the source of my download issue. not finding the jar were I was expecting to find it on maven, confused me to think this is a maven issue.
