### ISSUE TITLE
ResolveException: Not found

### ISSUE THREAD

**Issue by Emptyless** [julianpeeters/sbt-avrohugger#84]
When adding the plugin as defined in the README to the `build.sbt`:
```
addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "2.0.0-RC22")
```

The following exception is thrown upon loading the SBT changes:

```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.julianpeeters:sbt-avrohugger;sbtVersion=1.0;scalaVersion=2.13:2.0.0-RC22
[error]   Not found
```

**Comment by julianpeeters** [comment]
sorry to leave ya hangin,

I see that sbt is trying to resolve for scalaVersion 2.13, but sbt-avrohugger is only built for 2.12, since it's an sbt plugin. Please make sure to place `addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "2.0.0-RC22")` in a `.sbt` file _in the `project` directory of your repo, and not a `.sbt` file in the base directory of your repo.
